<?php

namespace addnpc
{
	$npcinit = array
		(
			'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
			'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
			'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
			'killnum' => 0,	'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
			'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
			'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
			'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
			'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
			'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
			'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
			'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
			'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
			'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
			'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
			'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		);
	$anpcinfo = array
		(
		7 => array
			(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
				'name' => '电击使 御坂 美琴',
				'icon' => 41,
				'gd' => 'f',
				'wep' => '【科学的超电磁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'ed',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				1 => array
				(
				'name' => '班主任 坂持 金发',
				'icon' => 42,
				'gd' => 'm',
				'wep' => '【水素粒子水铁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'id',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				2 => array
				(
				'name' => '花之领主 风见 幽香',
				'icon' => 43,
				'gd' => 'f',
				'wep' => '魔炮【元祖二重魔炮】',
				'wepk' => 'WF',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'pd',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
		
		12 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => 'Dark Force幼体',
				'icon' => 81,
				'wep' => 'RV『Black Riper』',
				'wepk' => 'WG',
				'wepe' => 80,
				'weps' => 125,
				'wepsk' => 'c',
				),
			),
		),
		
		13 => array(
			'mode' => 1,
			'num' => 2,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'teamID' => '',
			'teamPass' => '',
			'killnum' => 0,
			/*
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			*/
			'sub' => array(
				0 => array(
				'pose'=> 1,
				'tactic' => 3,
				'gd' => 'f',
				'pls' => 24,
				'mhp' => 8000,
				'msp' => 4000,
				'att' => 750,
				'def' => 750,
				'lvl' => 90,
				'club' => 98,
				'skills' => 14066,	//8号技能和12号技能
				//1600 * 第一技能編號 + 100 * 第二技能編號 + 10 * (第一技能的等級，最高6) + 1 * (第二技能的等級，最高6)
				//14066 = 1600 * 8 + 100 * 12 + 10 * 6 + 1 * 6
				//8 = 潜能
				//12 = 闪避
				'skill' => 800,
				'money' => 12000,
				'name' => '米可',	
				'icon' => 0,
				'wep' => '无后座力迷你加特林',
				'wepk' => 'WG',	'wepe' => 15,	'weps' => 100,	'wepsk' => 'or',
				'arb' => '星耀迷离的巫女服',
				'arbk' => 'DB',	'arbe' => 3000,	'arbs' => 3000,	'arbsk' => 'AbZ',
				'arh' => '猩红的缎带',
				'arhk' => 'DH',	'arhe' => 1444,	'arhs' => 3000,	'arhsk' => 'Z',
				'arf' => '云漆的木屐',
				'arfk' => 'DF',	'arfe' => 1444,	'arfs' => 3000,	'arfsk' => 'Z',
				'ara' => '白银的笼手',
				'arak' => 'DA',	'arae' => 1444,	'aras' => 3000,	'arask' => 'Z',
				'art' => '白诘草御社神的加护',
				'artk' => 'A',	'arte' => 1000,	'arts' => 1000,	'artsk' => 'Hv',
				'itm1' => '游戏解除钥匙',
				'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,
				'itm2' => '神仪【疾风迅雷】',
				'itmk2' => 'WCF',	'itme2' => 1500,	'itms2' => 9999,	'itmsk2' => 'ren',
				//'name' => '库特',
				//'icon' => 8,
				//'wep' => '光束镰刀',
				//'wepk' => 'WK',
				//'wepe' => 100,
				//'weps' => 36,
				//'wepsk' => 'ec',
				),
				1 => array
				(
				'name' => '书库联结 书库娘',
				'icon' => 0,
				'gd' => 'f',
				'pls' => 15,
				'mhp' => 30000,
				'msp' => 4000,
				'att' => 600,
				'def' => 600,
				'lvl' => 90,
				'club' => 22,//随便试试钢铁意志是什么称号
				'skill' => 750,
				'money' => 12000,
				//'skills' => 14066,
				'pose' => 1,
				'tactic' => 3,
				'wep' => '深渊百科全书真本',
				'wepk' => 'WF',
				'wepe' => 1,
				'weps' => 1,
				'arb' => '识别EX.B-可爱风格的围裙',
				'arbk' => 'DB',	'arbe' => 3000,	'arbs' => 3000,	'arbsk' => 'Ab',
				'arh' => '识别EX.H-百科才是本体',
				'arhk' => 'Dh',	'arhe' => 1444,	'arhs' => 3000,	'arhsk' => '',
				'arf' => '识别EX.F-时好时坏的服务器',
				'arfk' => 'DF',	'arfe' => 1444,	'arfs' => 3000,
				'ara' => '识别EX.A-不思议延迟重力',
				'arak' => 'DA',	'arae' => 1444,	'aras' => 3000,	'arask' => '',
				'art' => '深邃无限书库结界',
				'artk' => 'A',	'arte' => 1000,	'arts' => 1000,	'artsk' => 'aH',
				'itm1' => '游戏解除钥匙',
				'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 5,	'itmsk1' => '',
				/*
				'itm2' => '',
				'itmk2' => '',	'itme2' => ,	'itms2' => ,	'itmsk2' => '',
				'itm3' => '',
				'itmk3' => '',	'itme3' => ,	'itms3' => ,	'itmsk3' => '',
				'itm4' => '',
				'itmk4' => '',	'itme4' => ,	'itms4' => ,	'itmsk4' => '',
				'itm5' => '',
				'itmk5' => '',	'itme5' => ,	'itms5' => ,	'itmsk5' => '',
				*/
				),
			),
		), 
		16 => array(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'gd' => 'm',
			'pls' => 99,
			'mhp' => 2500,
			'msp' => 500,
			'att' => 1600,
			'def' => 3500,
			'lvl' => 50,
			'skill' => 750,
			'money' => 2000,
			'sub' => array
			(
				0 => array
				(
				'name' => '数纳 步',
				'icon' => 1600,
				'lvl' => 1,
				'mhp' => 4,
				'club' => 98,
				'wep' => '妖怪火车切',
				'wepk' => 'WK',	'wepe' => 800,	'weps' => 800,	'wepsk' => 'LrtXZ',
				'arb' => '简朴女式制服',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'cZ',
				'arf' => '助动装置',
				'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'SZ',
				'ara' => '装饰手镯',
				'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'MmZ',
				'art' => '森罗万象轮回之愿',
				'artk' => 'A',	'arte' => 1,	'arts' => 1,	'artsk' => 'ABabH',
				'itm1' => '含放射性添加剂的可乐',
				'itmk1' => 'HH',	'itme1' => 1600,	'itms1' => 8,	'itmsk1' => '',
				'itm2' => 'RPG7V1',
				'itmk2' => 'WG',	'itme2' => 1500,	'itms2' => 15,	'itmsk2' => 'dNotuwZ',
				'itm3' => '反器材狙击步枪',
				'itmk3' => 'WJ',	'itme3' => 3200,	'itms3' => 5,	'itmsk3' => 'notvXx',
				'itm4' => '九老人的手记卷轴',
				'itmk4' => 'Y',	'itme4' => 1,	'itms4' => 1,	'itmsk4' => '',
				'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
				'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
				),
				1 => array
				(
				'name' => '北大路 真',
				'icon' => 1601,
				'club' => 9,
				'wep' => '大亚光的超能力者用201型力场绝缘炮',
				'wepk' => 'WCF',
				'wepe' => 750,
				'weps' => '∞',
				'wepsk' => 'dnrwt',
				'arb' => '女仆装款式的特制作战服',
				'arbk' => 'DB',
				'arbe' => 888,
				'arbs' => 888,
				'arbsk' => 'bKGZ',
				'arh' => '荷叶边女仆头饰',
				'arhk' => 'DH',
				'arhe' => 888,
				'arhs' => 888,
				'arhsk' => 'AZ',
				'arf' => '女式皮鞋',
				'arfk' => 'DF',
				'arfe' => 888,
				'arfs' => 888,
				'art' => '十三将之证',
				'artk' => 'A',
				'arte' => 1,
				'arts' => 1,
				'artsk' => 'MmH',
				'itm1' => '北大路的便笺',
				'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1, 'itmsk1' => '',
				),
				2 => array
				(
				'name' => '五十铃川 兼元',
				'icon' => 1602,
				'gd' => 'f',
				'club' => 9,
				'pose'=> 4,
				'tactic' => 4,
				'mhp' => 1800,
				'wep' => '三日月宗近',
				'wepk' => 'WK',	'wepe' => 256,	'weps' => 999,	'wepsk' => 'eZ',
				'arb' => '黑色丝绸连衣裙',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'bKGZ',
				'arh' => '哥特萝莉塔发箍',
				'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'AabZ',
				'arf' => '女式皮鞋',
				'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,
				'art' => '九系统管理钥匙',
				'artk' => 'A',	'arte' => 1,	'arts' => 1,	'artsk' => 'MH',
				'itm1' => '大典太',
				'itmk1' => 'WK',	'itme1' => 256,	'itms1' => 999, 'itmsk1' => 'iZ',
				'itm2' => '鬼丸国纲',
				'itmk2' => 'WK',	'itme2' => 256,	'itms2' => 999, 'itmsk2' => 'uZ',
				'itm3' => '小乌丸天国',
				'itmk3' => 'WK',	'itme3' => 256,	'itms3' => 999, 'itmsk3' => 'wZ',
				'itm4' => '数珠丸恒次',
				'itmk4' => 'WK',	'itme4' => 256,	'itms4' => 999, 'itmsk4' => 'pZ',
				),
			),
		),
		17 => array(
			'num' => 5,
			'pass' => 'bra',
			'icon' => 0,
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'pls' => 22,
			'mhp' => 2500,
			'msp' => 200,
			'att' => 88,
			'def' => 88,
			'lvl' => 30,
			'skill' => 100,
			'money' => 888,
			'icon' => 0,
			'wep' => '？？？',
			'wepk' => 'WN',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
			'arb' => '深渊迷雾',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'v',
			'arh' => '深渊迷雾',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'v',
			'arf' => '深渊迷雾',
			'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'v',
			'ara' => '深渊迷雾',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'v',
			'art' => '深渊迷雾',
			'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'Hv',
			'sub' => array
			(
				0 => array
				(
				'name' => '白后娜美',
				'icon' => 0,
				'wep' => '不知从哪里拆下来的钢管',
				'wepk' => 'WP',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'rnv',
				'arb' => '白色连衣裙',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'A',
				'arh' => '白色发卡',
				'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => '',
				'arf' => '白色凉鞋',
				'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => '',
				'ara' => '白色腕环',
				'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'z',
				'art' => '白色十字架项链',
				'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'aH',
				),
				1 => array
				(
				'name' => '怀特迈恩准将',
				'icon' => 0,
				'gd' => 'f',
				'skill' => 600,
				'pose' => 4,
				'wep' => 'X-32激光枪',
				'wepk' => 'WG',	'wepe' => 150,	'weps' => 10,	'wepsk' => 'v',
				'arb' => '拟态护甲',
				'arbk' => 'DB',	'arbe' => 50,	'arbs' => 60,	'arbsk' => '',
				'arh' => '钢盔',
				'arhk' => 'DH',	'arhe' => 40,	'arhs' => 20,	'arhsk' => '',
				'arf' => '帝国标配军靴',
				'arfk' => 'DF',	'arfe' => 25,	'arfs' => 50,	'arfsk' => '',
				'ara' => '拟肤手套',
				'arak' => 'DA',	'arae' => 40,	'aras' => 40,	'arask' => '',
				'art' => '帝国的荣耀戒指',
				'artk' => 'A',	'arte' => 40,	'arts' => 20,	'artsk' => 'vH',			
				),
				2 => array
				(
				'name' => '镰刀子',
				'icon' => 0,
				'gd' => 'f',
				'wep' => '镰刀',
				'wepk' => 'WK',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
				'arb' => '午夜斗篷',
				'arbk' => 'DB',	'arbe' => 88,	'arbs' => 888,	'arbsk' => '',
				'art' => '巡夜提灯',
				'artk' => 'A',	'arte' => 40,	'arts' => 20,	'artsk' => 'vH',			
				),
				3 => array
				(
				'name' => '河童',
				'icon' => 0,
				'skill' => 600,
				'pose' => 4,
				'wep' => 'Lucifer本子',
				'wepk' => 'WF',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
				'arb' => '水手服',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => '',
				'arh' => '蝴蝶结',
				'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => '',
				'ara' => '白手套',
				'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => '',
				'art' => '项圈',
				'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'vH',			
				),
				4 => array
				(
				'name' => '邪心梦魇',
				'icon' => 0,
				'gd' => 'r',
				'skill' => 600,
				'pose' => 1,
				'tactic' => 2,
				'wep' => '血誓',
				'wepk' => 'WN',	'wepe' => 1300,	'weps' => 50,	'wepsk' => 'n=v',
				'arb' => '血食翼服',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'a',
				'arh' => '魇之角',
				'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'A',
				'art' => '魇纹',
				'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'lVH',			
				),
			),
		),
		
		/*
		4 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 33,
			'mhp' => 300,
			'msp' => 400,
			'att' => 800000,
			'def' => 800000,
			'lvl' => 250,
			'skill' => 50000,
			'money' => 1,
			'arb' => '黑色连衣裙',
			'arbk' => 'DB',
			'arbe' => 800,
			'arbs' => 20,
			'arbsk' => 'Aa',
			'arh' => '红色的丝带',
			'arhk' => 'DH',
			'arhe' => 800,
			'arhs' => 15,
			'arhsk' => 'B',
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 800,
			'arfs' => 21,
			'ara' => '红色的丝带',
			'arak' => 'DA',
			'arae' => 800,
			'aras' => 15,
			'arask' => 'b',
			'art' => '十字发卡',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '■',
				'icon' => 83,
				'wep' => '红色的丝带',
				'wepk' => 'WP',
				'wepe' => 800,
				'weps' => 20,
				'wepsk' => 'u',
				),
			),
		),
		7 => array
			(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
				'name' => '电击使 御坂 美琴',
				'icon' => 41,
				'gd' => 'f',
				'wep' => '【科学的超电磁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'ed',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				1 => array
				(
				'name' => '班主任 坂持 金发',
				'icon' => 42,
				'gd' => 'm',
				'wep' => '【水素粒子水铁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'id',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				2 => array
				(
				'name' => '花之领主 风见 幽香',
				'icon' => 43,
				'gd' => 'f',
				'wep' => '魔炮【元祖二重魔炮】',
				'wepk' => 'WF',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'pd',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
		
		12 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'skills' => array('401'=>'5'),
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => 'Dark Force幼体',
				'icon' => 81,
				'wep' => 'RV『Black Riper』',
				'wepk' => 'WG',
				'wepe' => 80,
				'weps' => 125,
				'wepsk' => 'c',
				),
			),
		),
		
		13 => array(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '库特',
				'icon' => 8,
				'wep' => '光束镰刀',
				'wepk' => 'WK',
				'wepe' => 100,
				'weps' => 36,
				'wepsk' => 'ec',
				),
			),
		),
		*/
	);
}

?>